#!/bin/bash
# Everything in this bootstrap script
# is idempotent. It is OK to run again
# on an existing project if you are
# uncertain whether it is set up.

git submodule update --init
bundle
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake test:all

echo "If this is the first time you've clone epic-auth"
echo "You might want to run \`bundle exec rake db:seed\`"
