#!/bin/bash

export RAILS_ENV=test
bundle

# Split these up into separate processes
# or we get the error `Application has been already initialized.`
bundle exec rake db:test:prepare
bundle exec rake test COVERAGE=on CI=true
