#!/bin/bash

export RAILS_ENV=test
export CI=true
export COVERAGE=on
bundle check || bundle

# Split these up into separate processes
# or we get the error `Application has been already initialized.`
bin/rails db:environment:set RAILS_ENV=test
bundle exec rake db:test:prepare
bundle exec rake test
